### ISSUE TITLE
Add synthetic data to existing datasets

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Classifier#119]
AS AN Architect
I WANT TO have a `REST` service to add synthetic data to existing datasets
SO THAT it would be generic service used throughout the system without code / service duplication

### Acceptance Criteria

- [ ] Service `schema` defined
- [ ] Synthetic data for any column can be fetched from various verified / pre-confirmed REST sources
- [ ] Service expects `source file`, `columns to be updated (by column nr)`, `external source to be added (by column nr)` `destination`

Example service `YAML` - TBC

```yaml
source_file: /full/path/to/source
destination: /full/path/to/destination
columns:
  fname:
    endpoint: https://ruuter.test.buerokratt.ee/synthetic-data/generate
    type: fname
    size: 1000
  email:
    endpoint: https://ruuter.test.buerokratt.ee/synthetic-data/generate
    type: email
    size: 1000
  villages_in_sri_lanka:
    endpoint: https://an.external.service/to/get/synthetic-data?q=villages_in_sri_lanka&size=1000
```

#### GUI

- [ ] GUI is out of scope of this issue

#### DSL

- [ ] `Ruuter`-based `REST` service
- [ ] `Postgres` to store state of current data manipulation process
- [ ] `CronManager` to initiate appropriate background triggers
- [ ] `S3 Ferry` for file transportation
